M48
; DRILL file {KiCad 8.0.4} date 2024-08-23T08:24:43+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-23T08:24:43+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X8.2764Y-4.8319
X8.5039Y-4.8319
T2
X3.2913Y-2.8543
X3.2913Y-4.9409
X9.315Y-2.8543
X9.315Y-4.9409
M30
