M48
; DRILL file {KiCad 8.0.0} date 2024-03-05T13:39:42+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-05T13:39:42+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X8.1776Y-4.8588
X8.4051Y-4.8588
T2
X3.2913Y-2.8543
X3.2913Y-4.9409
X9.315Y-2.8543
X9.315Y-4.9409
M30
